# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
sudo: true
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis codecov


script:
  # Run the tests without the used tools, to test if all exceptions are handled.
  - tox

  # Install tools used.
  - sudo apt-get install -y nmap

  # Run the tests again to test the other paths
  - tox

# Upload coverage report to codecov.io
after_success:
  - codecov

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: VanJanssen
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: VanJanssen/turret
    python: 2.7
